spring:
  application:
    name: springboot
  datasource:
   url: jdbc:mysql://localhost:3306/spring_learn_1
   username: root
   password: root
  jpa:
    hibernate:
      ddl-auto: create

server:
  port: 9000



blog:
  title: Blog
  url: https://abc.com
  a: hhhhhh
  b: oooooo
  banner:
    title: hi
